project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: "Página Inicial"
      - href: coleta.qmd
        text: Configuração
      - href: aed.qmd
        text: AED
      - href: modelo.qmd
        text: Modelagem
      - href: modelo2.qmd
        text: "Modelagem Alternativa"
      - about.qmd
    right:
      - icon: github
        href: https://github.com/NielsonAJR/ML_NBA

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Mostrar código"
    number-sections: true



